/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule PatientList.graphql
 * @generated SignedSource<<c38b2337115f808ad121482ac4876504>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type PatientList = {|
  +id: string;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": {
    "plural": true
  },
  "name": "PatientList",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "FragmentSpread",
      "name": "PatientName",
      "args": null
    }
  ],
  "type": "Patient"
};

module.exports = fragment;
