/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule PatientName.graphql
 * @generated SignedSource<<f63e8eff92ca1e9d2cf5e2d6457cae18>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type PatientName = {|
  +name: ?$ReadOnlyArray<?{|
    +text: ?string;
  |}>;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "PatientName",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "Humanname",
      "name": "name",
      "plural": true,
      "selections": [
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "text",
          "storageKey": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "Patient"
};

module.exports = fragment;
